In [1]:
import pandas as pd

In [2]:
# 1. Read Data & Handling Header Spaces (The First Trap):
# A
df = pd.read_csv('Data/data_nilai1.12expert.csv', sep=';')

In [3]:
df.head()

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi,Catatan_Mesin
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
1,L002,budi santoso,TRANSFER,"1,500,000",sukses,2024/05/02 09:20:00,-
2,L003,Andi,CEK SALDO,-,Gagal,03-05-2024 10:10:00,Timeout connection
3,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
4,L004,Joko,Setor Tunai,"-500,000",SUKSES,2024-05-04 11:30:00,System warning

In [4]:
# B
df.columns = df.columns.str.strip()

In [5]:
df.head()

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi,Catatan_Mesin
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
1,L002,budi santoso,TRANSFER,"1,500,000",sukses,2024/05/02 09:20:00,-
2,L003,Andi,CEK SALDO,-,Gagal,03-05-2024 10:10:00,Timeout connection
3,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
4,L004,Joko,Setor Tunai,"-500,000",SUKSES,2024-05-04 11:30:00,System warning