In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1. Read Data:
# A
df = pd.read_csv('Data/data_nilai1.14expert.csv', sep='\t') # sep='\t' yaitu untuk pemisah berupa tab

In [3]:
# B
df.columns = df.columns.str.strip() # Menghapus whitespace/spasi pada seluruh kolom tabel df

In [4]:
# 2. Removing Duplicates:
# A
df.drop_duplicates(subset=['Username', 'Teks_Tweet', 'Tanggal_Posting'], inplace=True)
"""
Perintah soal dengan:
"Cek dan hapus baris yang duplikat secara keseluruhan, lalu strip() nama kolom string untuk membuang spasi gaib.",
sudah dilakukan pada tugas 1 bagian B ya!
"""
df #

,Tweet_ID,Username,Teks_Tweet,Tanggal_Posting,Retweets,Likes
0,T001,@jokowi,Selamat pagi Indonesia! Mari bekerja. #Semanga...,01-Jan-2024,5.2K,15K
1,T002,@budi_santoso,Hari ini hujan lebat banget di Jakarta 🌧️,2024/01/02,150,1.2K
2,T003,@DataScienceID,Belajar Python dan Pandas sangat seru! 🔥 #Data...,Jan 03 2024,2.1K,10.5K
4,T004,@Siti_A,Macet parah di Sudirman... Kapan ya ada solusi...,04/01/2024,-50,300
5,T005,@tech_update,Iphone 16 rilis besok! Siapkan dompet kalian 📱,2024-01-05,1M,5.5M
6,T006,@Ani_Budi,Lagi pengen makan sate padang dekat rumah.,06-Jan-2024,NaN,NaN
7,T007,@budi_santoso,Hujan lagi hari ini...,2024/01/07,20,150
8,T008,@crypto_king,Bitcoin to the moon! 🚀🚀🚀 $BTC,Jan 08 2024,15K,45.2K
9,T009,@InfoBMKG,Peringatan dini cuaca ekstrim di wilayah Jawa ...,2024-01-09,10.5K,20K
10,T010,@Andi_123,Ga kerasa udah mau weekend aja nih.,10/01/2024,5,10
11,T011,@DataScienceID,Tips Pandas: Gunakan .apply() untuk manipulasi...,11-Jan-2024,3.5K,12K
12,T012,@Joko_P,Ada yang tau tempat ngopi enak di Bandung?,2024-01-12,12,55
13,T013,@tech_update,Rumor: PS6 akan dirilis tahun 2027.,Jan 13 2024,500,2.5K
14,T014,@InfoBMKG,Gempa bumi berkekuatan 5.0 SR di Maluku.,14/01/2024,8.2K,11K
15,T015,@Siti_A,Kereta telat lagi hari ini... Hadeh 🤦‍♀️,2024-01-15,-15,45
16,T016,@jokowi,Peresmian jalan tol baru di Sumatera.,16-Jan-2024,4.1K,25K
17,T017,@crypto_king,Ethereum juga ikut naik tajam! $ETH,2024/01/17,8.5K,30K
18,T018,@Ani_Budi,Akhirnya kesampaian juga makan sate padang!,Jan 18 2024,10,80
19,T019,@Joko_P,Kopi di kafe ini mantap banget! ☕,19/01/2024,25,120
21,T020,@bima_s,Selamat pagi semua!,2024-01-20,NaN,50

In [5]:
# 3. Cleaning Username:
# A
df['Username'] = df['Username'].str.replace('@', '')
df.head()

,Tweet_ID,Username,Teks_Tweet,Tanggal_Posting,Retweets,Likes
0,T001,jokowi,Selamat pagi Indonesia! Mari bekerja. #Semanga...,01-Jan-2024,5.2K,15K
1,T002,budi_santoso,Hari ini hujan lebat banget di Jakarta 🌧️,2024/01/02,150,1.2K
2,T003,DataScienceID,Belajar Python dan Pandas sangat seru! 🔥 #Data...,Jan 03 2024,2.1K,10.5K
4,T004,Siti_A,Macet parah di Sudirman... Kapan ya ada solusi...,04/01/2024,-50,300
5,T005,tech_update,Iphone 16 rilis besok! Siapkan dompet kalian 📱,2024-01-05,1M,5.5M

In [6]:
# B
df['Username'] = df['Username'].str.lower()
df.head()

,Tweet_ID,Username,Teks_Tweet,Tanggal_Posting,Retweets,Likes
0,T001,jokowi,Selamat pagi Indonesia! Mari bekerja. #Semanga...,01-Jan-2024,5.2K,15K
1,T002,budi_santoso,Hari ini hujan lebat banget di Jakarta 🌧️,2024/01/02,150,1.2K
2,T003,datascienceid,Belajar Python dan Pandas sangat seru! 🔥 #Data...,Jan 03 2024,2.1K,10.5K
4,T004,siti_a,Macet parah di Sudirman... Kapan ya ada solusi...,04/01/2024,-50,300
5,T005,tech_update,Iphone 16 rilis besok! Siapkan dompet kalian 📱,2024-01-05,1M,5.5M