In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1. Read Data:
# A
df = pd.read_csv('Data/data_nilai1.13expert.csv', sep='|')

In [3]:
# B
df.columns = df.columns.str.strip()

In [4]:
# 2. Removing Duplicates:
# A 
df.duplicated(subset=['ID_Properti', 'Tipe_Properti', 'Luas_Tanah', 'Sertifikat']).sum()
df.drop_duplicates(subset=['ID_Properti', 'Tipe_Properti', 'Luas_Tanah', 'Sertifikat'], inplace=True)

df['ID_Properti'] = df['ID_Properti'].str.strip()
df['Tipe_Properti'] = df['Tipe_Properti'].str.strip()
df['Luas_Tanah'] = df['Luas_Tanah'].str.strip()
df['Sertifikat'] = df['Sertifikat'].str.strip()


df.head()

,ID_Properti,Tipe_Properti,Luas_Tanah,Harga_Jual,Sertifikat,Tahun_Bangun
0,PRP-001,RUMAH,120 m2,"Rp 1,5 Milyar",SHM,2015
1,PRP-002,apartemen,45m2,Rp 500 Juta,HGB,2020
2,PRP-003,RUKO,100 m2,"2,5 Milyar",SHM,2018
4,PRP-004,rumah,90,Rp 800 Juta,SHM,2010
5,PRP-005,VILLA,500 m2,Rp 5 Milyar,HGB,2022

In [5]:
# 3. Cleaning Text:
# A
df['Tipe_Properti'] = df['Tipe_Properti'].str.title()

In [6]:
# B
df['Sertifikat'] = df['Sertifikat'].str.upper()
df.head(10)

,ID_Properti,Tipe_Properti,Luas_Tanah,Harga_Jual,Sertifikat,Tahun_Bangun
0,PRP-001,Rumah,120 m2,"Rp 1,5 Milyar",SHM,2015
1,PRP-002,Apartemen,45m2,Rp 500 Juta,HGB,2020
2,PRP-003,Ruko,100 m2,"2,5 Milyar",SHM,2018
4,PRP-004,Rumah,90,Rp 800 Juta,SHM,2010
5,PRP-005,Villa,500 m2,Rp 5 Milyar,HGB,2022
6,PRP-006,Apartemen,35 m2,450 Juta,STRATA TITLE,2021
7,PRP-007,Rumah,-150 m2,"Rp 1,2 Milyar",SHM,2019
8,PRP-008,Ruko,120m2,Rp 3 Milyar,HGB,NaN
9,PRP-009,Rumah,200 m2,Rp 2 Milyar,SHM,2017
10,PRP-010,Apartemen,50 m2,Rp 600 Juta,HGB,2018

In [7]:
# 4. Cleaning Luas_Tanah:
# A
df['Luas_Tanah'] = df['Luas_Tanah'].str.replace('m2', '').str.strip()
df.head()

,ID_Properti,Tipe_Properti,Luas_Tanah,Harga_Jual,Sertifikat,Tahun_Bangun
0,PRP-001,Rumah,120,"Rp 1,5 Milyar",SHM,2015
1,PRP-002,Apartemen,45,Rp 500 Juta,HGB,2020
2,PRP-003,Ruko,100,"2,5 Milyar",SHM,2018
4,PRP-004,Rumah,90,Rp 800 Juta,SHM,2010
5,PRP-005,Villa,500,Rp 5 Milyar,HGB,2022

In [8]:
# B
df['Luas_Tanah'] = df['Luas_Tanah'].astype(float)
df.head()

,ID_Properti,Tipe_Properti,Luas_Tanah,Harga_Jual,Sertifikat,Tahun_Bangun
0,PRP-001,Rumah,120.0,"Rp 1,5 Milyar",SHM,2015
1,PRP-002,Apartemen,45.0,Rp 500 Juta,HGB,2020
2,PRP-003,Ruko,100.0,"2,5 Milyar",SHM,2018
4,PRP-004,Rumah,90.0,Rp 800 Juta,SHM,2010
5,PRP-005,Villa,500.0,Rp 5 Milyar,HGB,2022

In [9]:
# C
df['Luas_Tanah'] = df['Luas_Tanah'].abs()
df.head(10)

,ID_Properti,Tipe_Properti,Luas_Tanah,Harga_Jual,Sertifikat,Tahun_Bangun
0,PRP-001,Rumah,120.0,"Rp 1,5 Milyar",SHM,2015
1,PRP-002,Apartemen,45.0,Rp 500 Juta,HGB,2020
2,PRP-003,Ruko,100.0,"2,5 Milyar",SHM,2018
4,PRP-004,Rumah,90.0,Rp 800 Juta,SHM,2010
5,PRP-005,Villa,500.0,Rp 5 Milyar,HGB,2022
6,PRP-006,Apartemen,35.0,450 Juta,STRATA TITLE,2021
7,PRP-007,Rumah,150.0,"Rp 1,2 Milyar",SHM,2019
8,PRP-008,Ruko,120.0,Rp 3 Milyar,HGB,NaN
9,PRP-009,Rumah,200.0,Rp 2 Milyar,SHM,2017
10,PRP-010,Apartemen,50.0,Rp 600 Juta,HGB,2018

In [10]:
# D
median_luas_tanah = df['Luas_Tanah'].median()
df.fillna({'Luas_Tanah': median_luas_tanah}, inplace=True)
df

,ID_Properti,Tipe_Properti,Luas_Tanah,Harga_Jual,Sertifikat,Tahun_Bangun
0,PRP-001,Rumah,120.0,"Rp 1,5 Milyar",SHM,2015
1,PRP-002,Apartemen,45.0,Rp 500 Juta,HGB,2020
2,PRP-003,Ruko,100.0,"2,5 Milyar",SHM,2018
4,PRP-004,Rumah,90.0,Rp 800 Juta,SHM,2010
5,PRP-005,Villa,500.0,Rp 5 Milyar,HGB,2022
6,PRP-006,Apartemen,35.0,450 Juta,STRATA TITLE,2021
7,PRP-007,Rumah,150.0,"Rp 1,2 Milyar",SHM,2019
8,PRP-008,Ruko,120.0,Rp 3 Milyar,HGB,NaN
9,PRP-009,Rumah,200.0,Rp 2 Milyar,SHM,2017
10,PRP-010,Apartemen,50.0,Rp 600 Juta,HGB,2018
11,PRP-011,Ruko,120.0,"Rp 1,8 Milyar",SHM,2016
12,PRP-012,Villa,1000.0,10 Milyar,SHM,2023
13,PRP-013,Rumah,110.0,Rp 900 Juta,SHM,2014
14,PRP-014,Apartemen,40.0,Rp 550 Juta,STRATA TITLE,2020
15,PRP-015,Ruko,150.0,Rp 4 Milyar,HGB,2015
16,PRP-016,Rumah,130.0,"Rp 1,3 Milyar",SHM,2021
17,PRP-017,Villa,600.0,Rp 6 Milyar,SHM,NaN
18,PRP-018,Apartemen,60.0,750 Juta,HGB,2019
19,PRP-019,Rumah,140.0,"Rp 1,4 Milyar",SHM,2018
20,PRP-020,Ruko,110.0,"Rp 2,2 Milyar",SHM,2020