In [1]:
import pandas as pd

In [2]:
# 1. Read Data & Handling Header Spaces (The First Trap):
# A
df = pd.read_csv('Data/data_nilai1.12expert.csv', sep=';')

In [3]:
df.head()

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi,Catatan_Mesin
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
1,L002,budi santoso,TRANSFER,"1,500,000",sukses,2024/05/02 09:20:00,-
2,L003,Andi,CEK SALDO,-,Gagal,03-05-2024 10:10:00,Timeout connection
3,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
4,L004,Joko,Setor Tunai,"-500,000",SUKSES,2024-05-04 11:30:00,System warning

In [4]:
# B
df.columns = df.columns.str.strip()

In [5]:
df.head()

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi,Catatan_Mesin
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
1,L002,budi santoso,TRANSFER,"1,500,000",sukses,2024/05/02 09:20:00,-
2,L003,Andi,CEK SALDO,-,Gagal,03-05-2024 10:10:00,Timeout connection
3,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
4,L004,Joko,Setor Tunai,"-500,000",SUKSES,2024-05-04 11:30:00,System warning

In [12]:
# 2. Removing Duplicates & Useless Columns:
# A 
df.duplicated(subset=['Nama_Nasabah', 'Tipe_Transaksi', 'Waktu_Transaksi']).sum()
df.drop_duplicates(subset=['Nama_Nasabah', 'Tipe_Transaksi', 'Waktu_Transaksi'])

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi,Catatan_Mesin
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
1,L002,budi santoso,TRANSFER,"1,500,000",sukses,2024/05/02 09:20:00,-
2,L003,Andi,CEK SALDO,-,Gagal,03-05-2024 10:10:00,Timeout connection
4,L004,Joko,Setor Tunai,"-500,000",SUKSES,2024-05-04 11:30:00,System warning
5,L005,Dewi,TRANSFER,NaN,gagal,05/05/2024 12:45:00,Insufficient funds
6,L006,rita sugiarto,tarik tunai,"1,200,000",SUKSES,2024-05-06 14:00:00,-
7,L007,Ahmad,Cek Saldo,-,sukses,07-05-2024 08:00:00,-
8,L008,PUTRI,Transfer,"250,000",GAGAL,2024/05/08 16:30:00,Network error
9,L009,bima,SETOR TUNAI,"1,000,000",sukses,2024-05-09 07:15:00,-
10,L010,Siti Aminah,tarik tunai,"-300,000",sukses,10/05/2024 10:20:00,-
11,L011,tono,TRANSFER,"5,000,000",Gagal,2024-05-11 11:11:00,Limit exceeded
12,L012,JOKO,Cek Saldo,-,SUKSES,12-05-2024 12:12:00,-
14,L013,dewi,SETOR TUNAI,"2,500,000",sukses,2024-05-13 13:13:00,-
15,L014,Andi,TRANSFER,NaN,GAGAL,14/05/2024 14:14:00,Destination account invalid
16,L015,rudi,tarik tunai,"1,000,000",sukses,2024-05-15 15:15:00,-
17,L016,SITI AMINAH,Transfer,"750,000",Sukses,16-05-2024 16:16:00,-
18,L017,budi santoso,CEK SALDO,-,Gagal,2024/05/17 17:17:00,PIN blocked
19,L018,Tono,SETOR TUNAI,"-150,000",SUKSES,2024-05-18 18:18:00,-
20,L019,Ahmad,Tarik Tunai,"2,000,000",sukses,19-05-2024 19:19:00,-
21,L020,rita sugiarto,Transfer,"3,000,000",GAGAL,2024-05-20 20:20:00,Timeout connection

In [14]:
# B 
df.drop(columns=['Catatan_Mesin']) # Menghapus kolom Catatan_Mesin

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00
1,L002,budi santoso,TRANSFER,"1,500,000",sukses,2024/05/02 09:20:00
2,L003,Andi,CEK SALDO,-,Gagal,03-05-2024 10:10:00
3,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00
4,L004,Joko,Setor Tunai,"-500,000",SUKSES,2024-05-04 11:30:00
5,L005,Dewi,TRANSFER,NaN,gagal,05/05/2024 12:45:00
6,L006,rita sugiarto,tarik tunai,"1,200,000",SUKSES,2024-05-06 14:00:00
7,L007,Ahmad,Cek Saldo,-,sukses,07-05-2024 08:00:00
8,L008,PUTRI,Transfer,"250,000",GAGAL,2024/05/08 16:30:00
9,L009,bima,SETOR TUNAI,"1,000,000",sukses,2024-05-09 07:15:00
10,L010,Siti Aminah,tarik tunai,"-300,000",sukses,10/05/2024 10:20:00
11,L011,tono,TRANSFER,"5,000,000",Gagal,2024-05-11 11:11:00
12,L012,JOKO,Cek Saldo,-,SUKSES,12-05-2024 12:12:00
13,L008,PUTRI,Transfer,"250,000",GAGAL,2024/05/08 16:30:00
14,L013,dewi,SETOR TUNAI,"2,500,000",sukses,2024-05-13 13:13:00
15,L014,Andi,TRANSFER,NaN,GAGAL,14/05/2024 14:14:00
16,L015,rudi,tarik tunai,"1,000,000",sukses,2024-05-15 15:15:00
17,L016,SITI AMINAH,Transfer,"750,000",Sukses,16-05-2024 16:16:00
18,L017,budi santoso,CEK SALDO,-,Gagal,2024/05/17 17:17:00
19,L018,Tono,SETOR TUNAI,"-150,000",SUKSES,2024-05-18 18:18:00
20,L019,Ahmad,Tarik Tunai,"2,000,000",sukses,19-05-2024 19:19:00
21,L020,rita sugiarto,Transfer,"3,000,000",GAGAL,2024-05-20 20:20:00