In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1. Read Data & Handling Header Spaces (The First Trap):
# A
df = pd.read_csv('Data/data_nilai1.12expert.csv', sep=';')

In [3]:
df.head()

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi,Catatan_Mesin
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
1,L002,budi santoso,TRANSFER,"1,500,000",sukses,2024/05/02 09:20:00,-
2,L003,Andi,CEK SALDO,-,Gagal,03-05-2024 10:10:00,Timeout connection
3,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
4,L004,Joko,Setor Tunai,"-500,000",SUKSES,2024-05-04 11:30:00,System warning

In [4]:
# B
df.columns = df.columns.str.strip()

In [5]:
df.head()

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi,Catatan_Mesin
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
1,L002,budi santoso,TRANSFER,"1,500,000",sukses,2024/05/02 09:20:00,-
2,L003,Andi,CEK SALDO,-,Gagal,03-05-2024 10:10:00,Timeout connection
3,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
4,L004,Joko,Setor Tunai,"-500,000",SUKSES,2024-05-04 11:30:00,System warning

In [6]:
# 2. Removing Duplicates & Useless Columns:
# A 
df.duplicated(subset=['Nama_Nasabah', 'Tipe_Transaksi', 'Waktu_Transaksi']).sum()
df = df.drop_duplicates(subset=['Nama_Nasabah', 'Tipe_Transaksi', 'Waktu_Transaksi'])

In [7]:
# B 
df.drop(columns=['Catatan_Mesin'], inplace=True) # Menghapus kolom Catatan_Mesin

In [8]:
# 3. Cleaning Wrong Data (Text Manipulation Chaining):
# A
df['Nama_Nasabah'] = df['Nama_Nasabah'].str.strip().str.title()

In [9]:
# B
df['Tipe_Transaksi'] = df['Tipe_Transaksi'].str.upper()
df['Status'] = df['Status'].str.upper()
df.head()

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00
1,L002,Budi Santoso,TRANSFER,"1,500,000",SUKSES,2024/05/02 09:20:00
2,L003,Andi,CEK SALDO,-,GAGAL,03-05-2024 10:10:00
4,L004,Joko,SETOR TUNAI,"-500,000",SUKSES,2024-05-04 11:30:00
5,L005,Dewi,TRANSFER,NaN,GAGAL,05/05/2024 12:45:00

In [10]:
# 4. Cleaning Wrong Format (Complex Formatting):
# A
df['Nominal_Rp'] = df['Nominal_Rp'].str.strip().replace('-', np.nan)
df.head(5)

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00
1,L002,Budi Santoso,TRANSFER,"1,500,000",SUKSES,2024/05/02 09:20:00
2,L003,Andi,CEK SALDO,NaN,GAGAL,03-05-2024 10:10:00
4,L004,Joko,SETOR TUNAI,"-500,000",SUKSES,2024-05-04 11:30:00
5,L005,Dewi,TRANSFER,NaN,GAGAL,05/05/2024 12:45:00

In [11]:
# B
df['Nominal_Rp'] = df['Nominal_Rp'].str.replace(',', '')
df.head(5)

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi
0,L001,Siti Aminah,TARIK TUNAI,500000,GAGAL,2024-05-01 08:15:00
1,L002,Budi Santoso,TRANSFER,1500000,SUKSES,2024/05/02 09:20:00
2,L003,Andi,CEK SALDO,NaN,GAGAL,03-05-2024 10:10:00
4,L004,Joko,SETOR TUNAI,-500000,SUKSES,2024-05-04 11:30:00
5,L005,Dewi,TRANSFER,NaN,GAGAL,05/05/2024 12:45:00

In [12]:
# C
df['Nominal_Rp'] = df['Nominal_Rp'].astype(float)
df.head(5)

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi
0,L001,Siti Aminah,TARIK TUNAI,500000.0,GAGAL,2024-05-01 08:15:00
1,L002,Budi Santoso,TRANSFER,1500000.0,SUKSES,2024/05/02 09:20:00
2,L003,Andi,CEK SALDO,NaN,GAGAL,03-05-2024 10:10:00
4,L004,Joko,SETOR TUNAI,-500000.0,SUKSES,2024-05-04 11:30:00
5,L005,Dewi,TRANSFER,NaN,GAGAL,05/05/2024 12:45:00

In [13]:
# D
df['Waktu_Transaksi'] = pd.to_datetime(df['Waktu_Transaksi'], format='mixed', dayfirst=True)
df.head()

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi
0,L001,Siti Aminah,TARIK TUNAI,500000.0,GAGAL,2024-05-01 08:15:00
1,L002,Budi Santoso,TRANSFER,1500000.0,SUKSES,2024-05-02 09:20:00
2,L003,Andi,CEK SALDO,NaN,GAGAL,2024-05-03 10:10:00
4,L004,Joko,SETOR TUNAI,-500000.0,SUKSES,2024-05-04 11:30:00
5,L005,Dewi,TRANSFER,NaN,GAGAL,2024-05-05 12:45:00