In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1. Read Data:
# A
df = pd.read_csv('Data/data_nilai1.13expert.csv', sep='|')

In [3]:
# B
df.columns = df.columns.str.strip() # Menghapus whitespace / spasi pada setiap kolom

In [4]:
# 2. Removing Duplicates:
# A 
df.duplicated(subset=['ID_Properti', 'Tipe_Properti', 'Luas_Tanah', 'Sertifikat']).sum() # Menghitung nilai duplikat 
df.drop_duplicates(subset=['ID_Properti', 'Tipe_Properti', 'Luas_Tanah', 'Sertifikat'], inplace=True)

df['ID_Properti'] = df['ID_Properti'].str.strip()
df['Tipe_Properti'] = df['Tipe_Properti'].str.strip()
df['Luas_Tanah'] = df['Luas_Tanah'].str.strip()
df['Sertifikat'] = df['Sertifikat'].str.strip()


df.head()

,ID_Properti,Tipe_Properti,Luas_Tanah,Harga_Jual,Sertifikat,Tahun_Bangun
0,PRP-001,RUMAH,120 m2,"Rp 1,5 Milyar",SHM,2015
1,PRP-002,apartemen,45m2,Rp 500 Juta,HGB,2020
2,PRP-003,RUKO,100 m2,"2,5 Milyar",SHM,2018
4,PRP-004,rumah,90,Rp 800 Juta,SHM,2010
5,PRP-005,VILLA,500 m2,Rp 5 Milyar,HGB,2022

In [5]:
# 3. Cleaning Text:
# A
df['Tipe_Properti'] = df['Tipe_Properti'].str.title() # Mengubah nilai pada kolom Tipe_Properti menjadi tulisan kapital per-kata

In [6]:
# B
df['Sertifikat'] = df['Sertifikat'].str.upper() # Mengubah nilai pada kolom Sertifikat menjadi tulisan kapital semua
df.head(10)

,ID_Properti,Tipe_Properti,Luas_Tanah,Harga_Jual,Sertifikat,Tahun_Bangun
0,PRP-001,Rumah,120 m2,"Rp 1,5 Milyar",SHM,2015
1,PRP-002,Apartemen,45m2,Rp 500 Juta,HGB,2020
2,PRP-003,Ruko,100 m2,"2,5 Milyar",SHM,2018
4,PRP-004,Rumah,90,Rp 800 Juta,SHM,2010
5,PRP-005,Villa,500 m2,Rp 5 Milyar,HGB,2022
6,PRP-006,Apartemen,35 m2,450 Juta,STRATA TITLE,2021
7,PRP-007,Rumah,-150 m2,"Rp 1,2 Milyar",SHM,2019
8,PRP-008,Ruko,120m2,Rp 3 Milyar,HGB,NaN
9,PRP-009,Rumah,200 m2,Rp 2 Milyar,SHM,2017
10,PRP-010,Apartemen,50 m2,Rp 600 Juta,HGB,2018

In [7]:
# 4. Cleaning Luas_Tanah:
# A
df['Luas_Tanah'] = df['Luas_Tanah'].str.replace('m2', '').str.strip() # Mengganti nilai 'm2' dengan string kosong, lalu menghapus whitespace/spasi
df.head()

,ID_Properti,Tipe_Properti,Luas_Tanah,Harga_Jual,Sertifikat,Tahun_Bangun
0,PRP-001,Rumah,120,"Rp 1,5 Milyar",SHM,2015
1,PRP-002,Apartemen,45,Rp 500 Juta,HGB,2020
2,PRP-003,Ruko,100,"2,5 Milyar",SHM,2018
4,PRP-004,Rumah,90,Rp 800 Juta,SHM,2010
5,PRP-005,Villa,500,Rp 5 Milyar,HGB,2022

In [8]:
# B
df['Luas_Tanah'] = df['Luas_Tanah'].astype(float) # Mengubah tipe data pada kolom 'Luas_Tanah' menjadi float
df.head()

,ID_Properti,Tipe_Properti,Luas_Tanah,Harga_Jual,Sertifikat,Tahun_Bangun
0,PRP-001,Rumah,120.0,"Rp 1,5 Milyar",SHM,2015
1,PRP-002,Apartemen,45.0,Rp 500 Juta,HGB,2020
2,PRP-003,Ruko,100.0,"2,5 Milyar",SHM,2018
4,PRP-004,Rumah,90.0,Rp 800 Juta,SHM,2010
5,PRP-005,Villa,500.0,Rp 5 Milyar,HGB,2022

In [9]:
# C
df['Luas_Tanah'] = df['Luas_Tanah'].abs() # Mengubah nilai pada kolom Luas_Tanah menjadi absolut
df.head(10)

,ID_Properti,Tipe_Properti,Luas_Tanah,Harga_Jual,Sertifikat,Tahun_Bangun
0,PRP-001,Rumah,120.0,"Rp 1,5 Milyar",SHM,2015
1,PRP-002,Apartemen,45.0,Rp 500 Juta,HGB,2020
2,PRP-003,Ruko,100.0,"2,5 Milyar",SHM,2018
4,PRP-004,Rumah,90.0,Rp 800 Juta,SHM,2010
5,PRP-005,Villa,500.0,Rp 5 Milyar,HGB,2022
6,PRP-006,Apartemen,35.0,450 Juta,STRATA TITLE,2021
7,PRP-007,Rumah,150.0,"Rp 1,2 Milyar",SHM,2019
8,PRP-008,Ruko,120.0,Rp 3 Milyar,HGB,NaN
9,PRP-009,Rumah,200.0,Rp 2 Milyar,SHM,2017
10,PRP-010,Apartemen,50.0,Rp 600 Juta,HGB,2018

In [10]:
# D
median_luas_tanah = df['Luas_Tanah'].median() # Mencari nilai median pada kolom Luas_Tanah
df.fillna({'Luas_Tanah': median_luas_tanah}, inplace=True)
df

,ID_Properti,Tipe_Properti,Luas_Tanah,Harga_Jual,Sertifikat,Tahun_Bangun
0,PRP-001,Rumah,120.0,"Rp 1,5 Milyar",SHM,2015
1,PRP-002,Apartemen,45.0,Rp 500 Juta,HGB,2020
2,PRP-003,Ruko,100.0,"2,5 Milyar",SHM,2018
4,PRP-004,Rumah,90.0,Rp 800 Juta,SHM,2010
5,PRP-005,Villa,500.0,Rp 5 Milyar,HGB,2022
6,PRP-006,Apartemen,35.0,450 Juta,STRATA TITLE,2021
7,PRP-007,Rumah,150.0,"Rp 1,2 Milyar",SHM,2019
8,PRP-008,Ruko,120.0,Rp 3 Milyar,HGB,NaN
9,PRP-009,Rumah,200.0,Rp 2 Milyar,SHM,2017
10,PRP-010,Apartemen,50.0,Rp 600 Juta,HGB,2018
11,PRP-011,Ruko,120.0,"Rp 1,8 Milyar",SHM,2016
12,PRP-012,Villa,1000.0,10 Milyar,SHM,2023
13,PRP-013,Rumah,110.0,Rp 900 Juta,SHM,2014
14,PRP-014,Apartemen,40.0,Rp 550 Juta,STRATA TITLE,2020
15,PRP-015,Ruko,150.0,Rp 4 Milyar,HGB,2015
16,PRP-016,Rumah,130.0,"Rp 1,3 Milyar",SHM,2021
17,PRP-017,Villa,600.0,Rp 6 Milyar,SHM,NaN
18,PRP-018,Apartemen,60.0,750 Juta,HGB,2019
19,PRP-019,Rumah,140.0,"Rp 1,4 Milyar",SHM,2018
20,PRP-020,Ruko,110.0,"Rp 2,2 Milyar",SHM,2020

In [11]:
# 5. Cleaning Harga_Jual
# A
df['Harga_Jual'] = df['Harga_Jual'].str.strip().str.replace('Rp', '') # Menghapus whitespace/spasi, lalu mengganti 'Rp' dengan string kosong
df.head()

  ID_Properti Tipe_Properti  Luas_Tanah   Harga_Jual Sertifikat Tahun_Bangun
0     PRP-001         Rumah       120.0   1,5 Milyar        SHM         2015
1     PRP-002     Apartemen        45.0     500 Juta        HGB         2020
2     PRP-003          Ruko       100.0   2,5 Milyar        SHM         2018
4     PRP-004         Rumah        90.0     800 Juta        SHM         2010
5     PRP-005         Villa       500.0     5 Milyar        HGB         2022

In [12]:
# B
df['Harga_Jual'] = df['Harga_Jual'].str.replace(',', '.') # Mengganti ',' dengan '.'
df.head()

  ID_Properti Tipe_Properti  Luas_Tanah   Harga_Jual Sertifikat Tahun_Bangun
0     PRP-001         Rumah       120.0   1.5 Milyar        SHM         2015
1     PRP-002     Apartemen        45.0     500 Juta        HGB         2020
2     PRP-003          Ruko       100.0   2.5 Milyar        SHM         2018
4     PRP-004         Rumah        90.0     800 Juta        SHM         2010
5     PRP-005         Villa       500.0     5 Milyar        HGB         2022

In [13]:
# C
def removeNominal(teks) : # Sebuah fungsi untuk menghapus nominal pada teks
    if type(teks) == str : # Mengecek, apakah type data 'teks' sama dengan string
        if 'Juta' in teks : # Jika sama, lalu mengecek kata 'Juta' didalam teks
            angka_bersih = teks.replace('Juta', '').strip() # Membuat variabel untuk mengganti 'Juta' dengan string kosong, lalu menghapus whitespace/spasi
            return float(angka_bersih) * 1000000 # Lalu mengkonversi tipe data dari string ke float, lalu dikali dengan 1 juta
        elif 'Milyar' in teks :
            angka_bersih = teks.replace('Milyar', '').strip() # sama dengan penjelasan sebelumnya, pada 'Juta'
            return float(angka_bersih) * 1000000000
    return teks

df['Harga_Jual'] = df['Harga_Jual'].apply(removeNominal) # Digunakan untuk menerapkan fungsi kustom ke setiap elemen, baris, atau kolom dalam DataFrame
df.head()

  ID_Properti Tipe_Properti  Luas_Tanah    Harga_Jual Sertifikat Tahun_Bangun
0     PRP-001         Rumah       120.0  1.500000e+09        SHM         2015
1     PRP-002     Apartemen        45.0  5.000000e+08        HGB         2020
2     PRP-003          Ruko       100.0  2.500000e+09        SHM         2018
4     PRP-004         Rumah        90.0  8.000000e+08        SHM         2010
5     PRP-005         Villa       500.0  5.000000e+09        HGB         2022

In [14]:
# 6. Cleaning Tahun_Bangunan :
# A 
df['Tahun_Bangun'] = pd.to_numeric(df['Tahun_Bangun'], errors='coerce')
"""
Fungsi errors = 'coerce' adalah memaksa data yang gagal diubah ke angka menjadi kosong (NaN)

Saat mengonversi kolom menjadi tipe numerik, jika Pandas menemukan teks atau simbol (seperti tulisan " NaN " atau huruf), 
ia biasanya akan langsung memunculkan error dan menghentikan program.

Solusi adalah coerce pada Pandas mengabaikan error tersebut. Data yang bisa diubah akan menjadi angka, sementara data teks yang 
membandel akan secara paksa diganti menjadi NaN (Not a Number atau missing value resmi).
"""

mode_tahun_bangun = df['Tahun_Bangun'].mode()[0] # Menghitung modus/banyaknya data yang muncul pada kolom Tahun_Bangun
df.fillna({'Tahun_Bangun': mode_tahun_bangun}, inplace=True)

df['Tahun_Bangun'] = df['Tahun_Bangun'].astype(int) # Mengubah tipe data dari kolom Tahun_Bangun (string) ke int

In [15]:
# 7. Final Validation :
# A
df = df.reset_index(drop=True) # Mereset indeks yang sebelumnya sudah ada yang terhapus, ke indeks yang diurutkan dari awal lagi
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID_Properti    20 non-null     object
 1   Tipe_Properti  20 non-null     object
 2   Luas_Tanah     20 non-null     float64
 3   Harga_Jual     20 non-null     float64
 4   Sertifikat     20 non-null     object
 5   Tahun_Bangun   20 non-null     int64
dtypes: float64(2), int64(1), object(3)
memory usage: 1.1+ KB

,ID_Properti,Tipe_Properti,Luas_Tanah,Harga_Jual,Sertifikat,Tahun_Bangun
0,PRP-001,Rumah,120.0,1.500000e+09,SHM,2015
1,PRP-002,Apartemen,45.0,5.000000e+08,HGB,2020
2,PRP-003,Ruko,100.0,2.500000e+09,SHM,2018
3,PRP-004,Rumah,90.0,8.000000e+08,SHM,2010
4,PRP-005,Villa,500.0,5.000000e+09,HGB,2022
5,PRP-006,Apartemen,35.0,4.500000e+08,STRATA TITLE,2021
6,PRP-007,Rumah,150.0,1.200000e+09,SHM,2019
7,PRP-008,Ruko,120.0,3.000000e+09,HGB,2018
8,PRP-009,Rumah,200.0,2.000000e+09,SHM,2017
9,PRP-010,Apartemen,50.0,6.000000e+08,HGB,2018
10,PRP-011,Ruko,120.0,1.800000e+09,SHM,2016
11,PRP-012,Villa,1000.0,1.000000e+10,SHM,2023
12,PRP-013,Rumah,110.0,9.000000e+08,SHM,2014
13,PRP-014,Apartemen,40.0,5.500000e+08,STRATA TITLE,2020
14,PRP-015,Ruko,150.0,4.000000e+09,HGB,2015
15,PRP-016,Rumah,130.0,1.300000e+09,SHM,2021
16,PRP-017,Villa,600.0,6.000000e+09,SHM,2018
17,PRP-018,Apartemen,60.0,7.500000e+08,HGB,2019
18,PRP-019,Rumah,140.0,1.400000e+09,SHM,2018
19,PRP-020,Ruko,110.0,2.200000e+09,SHM,2020