In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1. Read Data & Handling Header Spaces (The First Trap):
# A
df = pd.read_csv('Data/data_nilai1.12expert.csv', sep=';')

In [3]:
df.head()

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi,Catatan_Mesin
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
1,L002,budi santoso,TRANSFER,"1,500,000",sukses,2024/05/02 09:20:00,-
2,L003,Andi,CEK SALDO,-,Gagal,03-05-2024 10:10:00,Timeout connection
3,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
4,L004,Joko,Setor Tunai,"-500,000",SUKSES,2024-05-04 11:30:00,System warning

In [4]:
# B
df.columns = df.columns.str.strip()

In [5]:
df.head()

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi,Catatan_Mesin
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
1,L002,budi santoso,TRANSFER,"1,500,000",sukses,2024/05/02 09:20:00,-
2,L003,Andi,CEK SALDO,-,Gagal,03-05-2024 10:10:00,Timeout connection
3,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00,Error code 102
4,L004,Joko,Setor Tunai,"-500,000",SUKSES,2024-05-04 11:30:00,System warning

In [6]:
# 2. Removing Duplicates & Useless Columns:
# A 
df.duplicated(subset=['Nama_Nasabah', 'Tipe_Transaksi', 'Waktu_Transaksi']).sum()
df = df.drop_duplicates(subset=['Nama_Nasabah', 'Tipe_Transaksi', 'Waktu_Transaksi'])
"""
Bisa menggunakan df.drop_duplicates(subset=['Nama_Nasabah', 'Tipe_Transaksi', 'Waktu_Transaksi'], inplace=True)
dengan tambahan inplace=True
"""

"\nBisa menggunakan df.drop_duplicates(subset=['Nama_Nasabah', 'Tipe_Transaksi', 'Waktu_Transaksi'], inplace=True)\ndengan tambahan inplace=True\n"

In [7]:
# B 
df.drop(columns=['Catatan_Mesin'], inplace=True) # Menghapus kolom Catatan_Mesin

In [8]:
# 3. Cleaning Wrong Data (Text Manipulation Chaining):
# A
df['Nama_Nasabah'] = df['Nama_Nasabah'].str.strip().str.title() # Mengubah tulisan menjadi kapital (per-kata)

In [9]:
# B
df['Tipe_Transaksi'] = df['Tipe_Transaksi'].str.strip().str.upper() # Mengubah ke dalam tulisan besar semua
df['Status'] = df['Status'].str.strip().str.upper() # Mengubah ke dalam tulisan besar semua
df.head()

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00
1,L002,Budi Santoso,TRANSFER,"1,500,000",SUKSES,2024/05/02 09:20:00
2,L003,Andi,CEK SALDO,-,GAGAL,03-05-2024 10:10:00
4,L004,Joko,SETOR TUNAI,"-500,000",SUKSES,2024-05-04 11:30:00
5,L005,Dewi,TRANSFER,NaN,GAGAL,05/05/2024 12:45:00

In [10]:
# 4. Cleaning Wrong Format (Complex Formatting):
# A
df['Nominal_Rp'] = df['Nominal_Rp'].str.strip().replace('-', np.nan) # Mengganti '-' dengan nilai NaN
df.head(5)

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi
0,L001,Siti Aminah,TARIK TUNAI,"500,000",GAGAL,2024-05-01 08:15:00
1,L002,Budi Santoso,TRANSFER,"1,500,000",SUKSES,2024/05/02 09:20:00
2,L003,Andi,CEK SALDO,NaN,GAGAL,03-05-2024 10:10:00
4,L004,Joko,SETOR TUNAI,"-500,000",SUKSES,2024-05-04 11:30:00
5,L005,Dewi,TRANSFER,NaN,GAGAL,05/05/2024 12:45:00

In [11]:
# B
df['Nominal_Rp'] = df['Nominal_Rp'].str.replace(',', '') # Mengganti ',' dengan string kosong
df.head(5)

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi
0,L001,Siti Aminah,TARIK TUNAI,500000,GAGAL,2024-05-01 08:15:00
1,L002,Budi Santoso,TRANSFER,1500000,SUKSES,2024/05/02 09:20:00
2,L003,Andi,CEK SALDO,NaN,GAGAL,03-05-2024 10:10:00
4,L004,Joko,SETOR TUNAI,-500000,SUKSES,2024-05-04 11:30:00
5,L005,Dewi,TRANSFER,NaN,GAGAL,05/05/2024 12:45:00

In [12]:
# C
df['Nominal_Rp'] = df['Nominal_Rp'].astype(float) # Mengubah tipe data dari string ke float
df.head(5)

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi
0,L001,Siti Aminah,TARIK TUNAI,500000.0,GAGAL,2024-05-01 08:15:00
1,L002,Budi Santoso,TRANSFER,1500000.0,SUKSES,2024/05/02 09:20:00
2,L003,Andi,CEK SALDO,NaN,GAGAL,03-05-2024 10:10:00
4,L004,Joko,SETOR TUNAI,-500000.0,SUKSES,2024-05-04 11:30:00
5,L005,Dewi,TRANSFER,NaN,GAGAL,05/05/2024 12:45:00

In [13]:
# D
df['Waktu_Transaksi'] = pd.to_datetime(df['Waktu_Transaksi'], format='mixed', dayfirst=True)
"""
Mengubah format Waktu_Transaksi dengan format digunakan untuk mengonversi kolom berisi berbagai format tanggal yang 
tidak konsisten secara otomatis, dengan memprioritaskan hari sebelum bulan
"""
df.head()

   ID_Log  Nama_Nasabah Tipe_Transaksi  Nominal_Rp  Status     Waktu_Transaksi
0   L001    Siti Aminah    TARIK TUNAI    500000.0   GAGAL 2024-05-01 08:15:00
1   L002   Budi Santoso       TRANSFER   1500000.0  SUKSES 2024-05-02 09:20:00
2   L003           Andi      CEK SALDO         NaN   GAGAL 2024-05-03 10:10:00
4   L004           Joko    SETOR TUNAI   -500000.0  SUKSES 2024-05-04 11:30:00
5   L005           Dewi       TRANSFER         NaN   GAGAL 2024-05-05 12:45:00

In [14]:
# 5. Cleaning Wrong Data (Logical Error):
# A
df['Nominal_Rp'] = df['Nominal_Rp'].abs()
df.head(5)

   ID_Log  Nama_Nasabah Tipe_Transaksi  Nominal_Rp  Status     Waktu_Transaksi
0   L001    Siti Aminah    TARIK TUNAI    500000.0   GAGAL 2024-05-01 08:15:00
1   L002   Budi Santoso       TRANSFER   1500000.0  SUKSES 2024-05-02 09:20:00
2   L003           Andi      CEK SALDO         NaN   GAGAL 2024-05-03 10:10:00
4   L004           Joko    SETOR TUNAI    500000.0  SUKSES 2024-05-04 11:30:00
5   L005           Dewi       TRANSFER         NaN   GAGAL 2024-05-05 12:45:00

In [15]:
# 6. Cleaning Empty Cells (Domain Logic Imputation):
# A. 
df.fillna({'Nominal_Rp': 0}, inplace=True) # Menyisipkan nilai 0 pada kolom Nominal_Rp dengan nilai kolom yang kosong (tidak ada nilai)
df.head(10)

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi
0,L001,Siti Aminah,TARIK TUNAI,500000.0,GAGAL,2024-05-01 08:15:00
1,L002,Budi Santoso,TRANSFER,1500000.0,SUKSES,2024-05-02 09:20:00
2,L003,Andi,CEK SALDO,0.0,GAGAL,2024-05-03 10:10:00
4,L004,Joko,SETOR TUNAI,500000.0,SUKSES,2024-05-04 11:30:00
5,L005,Dewi,TRANSFER,0.0,GAGAL,2024-05-05 12:45:00
6,L006,Rita Sugiarto,TARIK TUNAI,1200000.0,SUKSES,2024-05-06 14:00:00
7,L007,Ahmad,CEK SALDO,0.0,SUKSES,2024-05-07 08:00:00
8,L008,Putri,TRANSFER,250000.0,GAGAL,2024-05-08 16:30:00
9,L009,Bima,SETOR TUNAI,1000000.0,SUKSES,2024-05-09 07:15:00
10,L010,Siti Aminah,TARIK TUNAI,300000.0,SUKSES,2024-05-10 10:20:00

In [16]:
# 7. Final Validation & Simple Data Insight (Tugas Analis):
# A
df = df.reset_index(drop=True) # Mengubah ke indeks awal
df.head()

   ID_Log  Nama_Nasabah Tipe_Transaksi  Nominal_Rp  Status     Waktu_Transaksi
0   L001    Siti Aminah    TARIK TUNAI    500000.0   GAGAL 2024-05-01 08:15:00
1   L002   Budi Santoso       TRANSFER   1500000.0  SUKSES 2024-05-02 09:20:00
2   L003           Andi      CEK SALDO         0.0   GAGAL 2024-05-03 10:10:00
3   L004           Joko    SETOR TUNAI    500000.0  SUKSES 2024-05-04 11:30:00
4   L005           Dewi       TRANSFER         0.0   GAGAL 2024-05-05 12:45:00

In [17]:
# B
"""
Kenapa tidak menggunakan df.to_string()?

Karena saat ini saya menggunakan Jupyter Notebook, tidak menggunakan Python pada vscode,
yang dimana saya ingin output yang dikeluarkan itu berupa tabel secara real, bukan berupa teks,
mungkin untuk tugas 7 bagian B saya menggunakan cara ini, yang sebenarnya tidak jauh berbeda dengan
menggunakan df.to_string(), hanya yang membedakan output yang dikeluarkan berupa tabel utuh, bukan string.

Output berupa menampilkan keselurahan tabel pada dataset.
"""
df

,ID_Log,Nama_Nasabah,Tipe_Transaksi,Nominal_Rp,Status,Waktu_Transaksi
0,L001,Siti Aminah,TARIK TUNAI,500000.0,GAGAL,2024-05-01 08:15:00
1,L002,Budi Santoso,TRANSFER,1500000.0,SUKSES,2024-05-02 09:20:00
2,L003,Andi,CEK SALDO,0.0,GAGAL,2024-05-03 10:10:00
3,L004,Joko,SETOR TUNAI,500000.0,SUKSES,2024-05-04 11:30:00
4,L005,Dewi,TRANSFER,0.0,GAGAL,2024-05-05 12:45:00
5,L006,Rita Sugiarto,TARIK TUNAI,1200000.0,SUKSES,2024-05-06 14:00:00
6,L007,Ahmad,CEK SALDO,0.0,SUKSES,2024-05-07 08:00:00
7,L008,Putri,TRANSFER,250000.0,GAGAL,2024-05-08 16:30:00
8,L009,Bima,SETOR TUNAI,1000000.0,SUKSES,2024-05-09 07:15:00
9,L010,Siti Aminah,TARIK TUNAI,300000.0,SUKSES,2024-05-10 10:20:00
10,L011,Tono,TRANSFER,5000000.0,GAGAL,2024-05-11 11:11:00
11,L012,Joko,CEK SALDO,0.0,SUKSES,2024-05-12 12:12:00
12,L013,Dewi,SETOR TUNAI,2500000.0,SUKSES,2024-05-13 13:13:00
13,L014,Andi,TRANSFER,0.0,GAGAL,2024-05-14 14:14:00
14,L015,Rudi,TARIK TUNAI,1000000.0,SUKSES,2024-05-15 15:15:00
15,L016,Siti Aminah,TRANSFER,750000.0,SUKSES,2024-05-16 16:16:00
16,L017,Budi Santoso,CEK SALDO,0.0,GAGAL,2024-05-17 17:17:00
17,L018,Tono,SETOR TUNAI,150000.0,SUKSES,2024-05-18 18:18:00
18,L019,Ahmad,TARIK TUNAI,2000000.0,SUKSES,2024-05-19 19:19:00
19,L020,Rita Sugiarto,TRANSFER,3000000.0,GAGAL,2024-05-20 20:20:00

In [18]:
# C
df['Status'].value_counts() # Menghitung berapa jumlah nilai pada kolom Status

Status
SUKSES    12
GAGAL      8
Name: count, dtype: int64